### ISSUE TITLE
pgBackRest fails if encryption is enabled and repo1-cipher-pass is not set

### ISSUE THREAD

**Issue by cbenjemaa** [timescale/timescaledb-kubernetes#135]
https://github.com/timescale/timescaledb-kubernetes/blob/master/charts/timescaledb-single/values.yaml#L55
By default `pgBackRest` encryption is disabled. In case we want to use `aes-256-cbc` cipher, a passphrase is required by setting `repo1-cipher-pass` value. 

Example:
```yaml
backup:
  enabled: true
  pgBackRest:
    # https://pgbackrest.org/configuration.html
    process-max: 4
    start-fast: "y"
    repo1-retention-diff: 2
    repo1-retention-full: 2
    repo1-s3-region: eu-central-1
    repo1-s3-bucket: <backup_name>
    repo1-s3-endpoint: s3.amazonaws.com
    repo1-type: s3
    repo1-cipher-type: aes-256-cbc
    repo1-cipher-pass: <long_passphrase_for_encryption>
```

**Comment by feikesteenbergen** [comment]
Other then documenting this, I don't think there is anything we can do here? Could you elaborate on what you think should happen?

**Comment by feikesteenbergen** [comment]
I think going forward, the best way to do these kind of things is by using 
kubernetes secrets, for example:

```console
kubectl create secret generic pgbackrest-secrets \
  --from-literal=PGBACKREST_REPO1_S3_KEY=examplekeyid \
  --from-literal=PGBACKREST_REPO1_S3_KEY_SECRET=examplesecret+D48GXfDdtl823nlSRRv7dmB \
  --from-literal=PGBACKREST_REPO1_S3_BUCKET=<backup_name> \
  --from-literal=PGBACKREST_REPO1_CIPHER_PASS=<long_passphrase_for_encryption>
```

And this snippet from the `values.yaml`:

```yaml
backup:
  enabled: true
  pgBackRest:
    # https://pgbackrest.org/configuration.html
    process-max: 4
    start-fast: "y"
    repo1-retention-diff: 2
    repo1-retention-full: 2
    repo1-s3-region: eu-central-1
    repo1-s3-endpoint: s3.amazonaws.com
    repo1-type: s3
    repo1-cipher-type: aes-256-cbc
  envFrom:
  - secretRef:
      name: pgbackrest-secrets
```
