### ISSUE TITLE
Patroni list all timescaleDB servers but I have no leaders

### ISSUE THREAD

**Issue by throrin19** [timescale/timescaledb-kubernetes#179]
Hello,

I try to launch the single-node chart in my kubernetes cluster. But I have a big problem : I have a timeout on try to connecting to the server using AWS NLB for the leader service.

I try to connect to servers and launch `patronictl list`. I have the list of all my timescaleDB servers, but none of them is leader and the cluster is *uninitialized* : 

```
+ Cluster: timescaledb-single (uninitialized) +---------+----+-----------+
|        Member        |      Host     | Role |  State  | TL | Lag in MB |
+----------------------+---------------+------+---------+----+-----------+
| timescaledb-single-0 | 172.31.13.213 |      | running |  1 |         0 |
| timescaledb-single-1 | 172.31.32.227 |      | running |  1 |         0 |
| timescaledb-single-2 |  172.31.25.84 |      | running |  1 |         0 |
+----------------------+---------------+------+---------+----+-----------+
```

Is it normal ? 

This is my value.yml passed to the chart : 

```yaml
replicaCount: 3
loadBalancer:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
persistentVolumes:
  data:
    size: 10Gi
secretNames:
  credentials: credentials
  certificate: certificate
  # pgbackrest: pgbackrest
patroni:
  postgresql:
    pg_hba:
    - local     all             all                                   peer
    - hostssl   all             all                127.0.0.1/32       md5
    - hostssl   all             all                ::1/128            md5
    - hostssl   replication     standby            all                md5
    - hostssl   all             all                all                md5
    - host      all             all                all                md5
```
