### ISSUE TITLE
[ISSUE] two TimescaleDB pods are in same node

### ISSUE THREAD

**Issue by throrin19** [timescale/timescaledb-kubernetes#238]
**Describe the bug**
I have a cluster with 3 nodes : 

![image](https://user-images.githubusercontent.com/1394778/98001915-f2080a80-1ded-11eb-988a-69de8950d602.png)

When I create timescaleDB using single-node helm chart, I have 2 pods in same node.

![image](https://user-images.githubusercontent.com/1394778/98001165-9dfd2600-1ded-11eb-89ad-f8ed85605af6.png)

**To Reproduce**
- Have a cluster with 3 nodes. Create timescaleDB-single-node app
- After the publish, I have two pods in same node.

**Expected behavior**
Have each timescaleDB pods in different nodes

**Deployment**
- What is in your `values.yaml`
- What version of the Chart are you using?
- What is your Kubernetes Environment (for exampe: GKE, EKS, minikube, microk8s)

**Deployment**

This is my value.yaml responses : 

```yaml
replicaCount: 3
clusterName: migration
persistentVolumes:
  data:
    size: 512Gi
  wal:
    size: 20Gi
secretNames:
  credentials: credentials
  certificate: certificate
  pgbackrest: pgbackrest
sharedMemory:
  useMount: true
backup:
  enabled: true
  pgBackRest:
    repo1-s3-region: eu-west-1
    repo1-s3-endpoint: s3.amazonaws.com
env:
  - name: TIMESCALEDB_TELEMETRY
    value: "off"
```
