### ISSUE TITLE
Cannot specify securityContext container attribute

### ISSUE THREAD

**Issue by franck102** [timescale/timescaledb-kubernetes#240]
## This is an improvement requests!

**Describe the bug**
The timescaledb-single chart won't let you configure a securityContext container attribute.
This is required in Kubernetes clusters that use pod security policies (else the container start as root and postgres refuses to start):

```
containers:
        - name: timescaledb
          securityContext:
            allowPrivilegeEscalation: false
            runAsGroup: 1000
            runAsNonRoot: true
            runAsUser: 1000
```

We have to create a local copy of the chart to work around this issue.
