### ISSUE TITLE
the <release name>-config service created by the chart is missing required Helm labels

### ISSUE THREAD

**Issue by franck102** [timescale/timescaledb-kubernetes#241]
> Have a look at [Troubleshooting](https://github.com/timescale/timescaledb-kubernetes/blob/master/charts/timescaledb-single/admin-guide.md#troubleshooting) or some [Common Issues](https://github.com/timescale/timescaledb-kubernetes/blob/master/charts/timescaledb-single/admin-guide.md#common-issues)

**Describe the bug**
The resource below is missing require Helm labels, as a result it is not uninstalled by helm delete, and the next install fails:

```
# Source: dms-timescaledb/charts/timescaledb-single/templates/svc-timescaledb-config.yaml
# This file and its contents are licensed under the Apache License 2.0.
# Please see the included NOTICE for copyright information and LICENSE for a copy of the license.

apiVersion: v1
kind: Service
metadata:
  name: dms-timescaledb-config
  labels:
    app: dms-timescaledb
    chart: timescaledb-single-0.7.1
    release: dms-timescaledb
    heritage: Helm
    cluster-name: dms-timescaledb
...

```

**To Reproduce**
helm install timescaledb-single followed
helm delete timescaledb-single

**Expected behavior**
The <release name>-config should be removed, it isn't

**Deployment**
timescaledb-single used as a subchart:

```
timescaledb-single:
  image:
    tag: pg12.4-ts1.7.4-p2
  patroni:
    log:
      level: WARNING
    bootstrap:
      dcs:
        postgresql:
          parameters:
            ssl: off
            log_connections: off
            log_disconnections: off
            log_min_messages: notice
            max_worker_processes: 96
            max_parallel_workers: 64
            timescaledb.max_background_workers: 64
    postgresql:
      pg_hba:
        - local     all             postgres                              peer
        - local     all             all                                   md5
        - hostnossl   all             all                127.0.0.1/32       md5
        - hostnossl   all             all                ::1/128            md5
        - hostnossl   replication     standby            all                md5
        - hostnossl   all             all                all                md5
```

- What version of the Chart are you using?
```
apiVersion: v1
name: timescaledb-single
description: 'TimescaleDB HA Deployment.'
version: 0.7.1
```
- What is your Kubernetes Environment (for exampe: GKE, EKS, minikube, microk8s)
docker for Desktop, EKS

**Logs**
Sample log when trying to re-install with the service left behind:
```
+ helm -v 3 install dms-timescaledb dms-timescaledb -f dms-timescaledb/values.laptop.yaml -f dms-timescaledb/values.common.yaml -n dmp-monitoring --dependency-update --create-namespace
Error: rendered manifests contain a resource that already exists. Unable to continue with install: Service "dms-timescaledb-config" in namespace "dmp-monitoring" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: missing key "app.kubernetes.io/managed-by": must be set to "Helm"; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "dms-timescaledb"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "dmp-monitoring"

```
