### ISSUE TITLE
[ISSUE] timescaledb.max_background_workers is setted to 8 workers by default

### ISSUE THREAD

**Issue by throrin19** [timescale/timescaledb-kubernetes#244]
**Describe the bug**
I have many error messages in logs of `out of background workers`

**To Reproduce**
Launch new server with telemetry on and add jobs on one hypertable (drop chunk and compress)

**Expected behavior**
Jobs execution correctly without any `out of background workers`

**Deployment**

value.yaml
```yml
replicaCount: 3
clusterName: production
loadBalancer:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
replicaLoadBalancer:
  enabled: true
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
persistentVolumes:
  data:
    size: 512Gi
  wal:
    size: 20Gi
secretNames:
  credentials: credentials
  certificate: certificate
  pgbackrest: pgbackrest
sharedMemory:
  useMount: true
backup:
  enabled: true
  pgBackRest:
    repo1-s3-region: eu-west-1
    repo1-s3-endpoint: s3.amazonaws.com
patroni:
  postgresql:
    pg_hba:
    - local     all             postgres                              peer
    - local     all             all                                   md5
    - hostssl   all             all                127.0.0.1/32       md5
    - hostssl   all             all                ::1/128            md5
    - hostssl   replication     standby            all                md5
    - hostssl   all             all                all                md5
    - host      all             all                all                md5
env:
  - name: TIMESCALEDB_TELEMETRY
    value: "off"
pgBouncer:
  enabled: true
  config:
    ignore_startup_parameters: extra_float_digits
    client_tls_sslmode: prefer
affinityTemplate: |
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
          - key: aquassay.io/timescaledb
            operator: In
            values:
            - "true"
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
    - topologyKey: "kubernetes.io/hostname"
      labelSelector:
        matchLabels:
          app: {{ template "timescaledb.fullname" . }}
          release: {{ .Release.Name | quote }}
          cluster-name: {{ template "clusterName" . }}
```

**Logs**

```
2020-11-24 10:45:27 UTC [226]: [5fa68400.e2-4105713] @,app= [01000] WARNING:  failed to launch job 1000 "Drop Chunks Background Job": out of background workers
2020-11-24 10:45:27 UTC [226]: [5fa68400.e2-4105715] @,app= [01000] WARNING:  failed to launch job 1001 "Compress Chunks Background Job": out of background workers
```

**Edit** : 

I try to change directly this parameters with patroni config in yaml like this : 

```yaml
patroni:
  bootstrap:
    dcs:
      postgresql:
        max_worker_processes: 32
        max_parallel_workers: 16
        timescaledb.max_background_workers: 16
```

But `timescaledb-tune` override my changes. How to set this changes directly in timescaledb-tune ?
