### ISSUE TITLE
Store DB access credentials securely in K8s secret

### ISSUE THREAD

**Issue by marvin-hansen** [timescale/timescaledb-kubernetes#245]
**Describe the bug**

Default root credentials are stored in plain-text in the values.yaml file which leaves the default deployment open to multiple critical security issues.  

**To Reproduce**

wget https://github.com/timescale/timescaledb-kubernetes/blob/master/charts/timescaledb-multinode/values.yaml

 grep 'superuser' values.yaml

**Expected behavior**

Credentials in the values.yaml reference secrets managed in Kubernetes. 

https://kubernetes.io/docs/tasks/inject-data-application/distribute-credentials-secure/

** Details ** 

Per today, Dec/4, this affects commit abec6247e78b685d4dc075ed877ba02d0eac72f8 and most likely virtually all prior commits for both helm charts, single and multi-node.

** Rectification ** 

Update docs with some basic guidance of how to add a secret to Kubernetes, which  boils down to some simple steps: 

```
kubectl create secret generic access-node-root --from-literal=access-root-pw='tea'
kubectl create secret generic data-node-root --from-literal=data-root-pw='coffee'
```

Update values.yaml with something like:

```
 env:
    - name: ACCESS_ROOT_SECRET
      valueFrom:
        secretKeyRef:
          name: access-node-root
          key: access-root-pw
    - name: DATA_ROOT_SECRET
      valueFrom:
        secretKeyRef:
          name: data-node-root
          key: data-root-pw

# Credentials used by PostgreSQL
credentials:
  accessNode:
    superuser: ACCESS_ROOT_SECRET
  dataNode:
    superuser: DATA_ROOT_SECRET
```

Credentials in K8s are fairly easy to fix but add some basic security by default.
