### ISSUE TITLE
[ISSUE] Service does not define any selectors

### ISSUE THREAD

**Issue by TobiasJacob** [timescale/timescaledb-kubernetes#384]
**Describe the bug**
Right now, svc-timescaledb.yaml is not defining any selectors. Hence, the resulting timescaledb service will not select any pods to forward the request to, and will not work. I suggest to add the following lines to the Service.

```yaml
  selector:
    app: {{ template "timescaledb.fullname" . }}
    cluster-name: {{ template "clusterName" . }}
```

I also suggest changing the name of the service to `release-name-timescaledb` to avoid conflicts with other charts in the same release that also setup a service using only the release name. 

```yaml
# This file and its contents are licensed under the Apache License 2.0.
# Please see the included NOTICE for copyright information and LICENSE for a copy of the license.

apiVersion: v1
kind: Service
metadata:
  name: {{ template "clusterName" . }}
  labels:
    app: {{ template "timescaledb.fullname" . }}
    chart: {{ template "timescaledb.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    cluster-name: {{ template "clusterName" . }}
    role: master
...
```

becomes

```yaml
# This file and its contents are licensed under the Apache License 2.0.
# Please see the included NOTICE for copyright information and LICENSE for a copy of the license.

apiVersion: v1
kind: Service
metadata:
  name: {{ template "timescaledb.fullname" . }}
  labels:
    app: {{ template "timescaledb.fullname" . }}
    chart: {{ template "timescaledb.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    cluster-name: {{ template "timescaledb.fullname" . }}
    role: master
...
```

(setting name and app field to {{ template "timescaledb.fullname" . }})

**To Reproduce**

On minikube, run:

```
helm install prototype timescaledb/timescaledb-single
```

Then use the minikube dashboard or `kubectl get endpoints prototype-timescaledb` to verify that no pods match the service.

**Expected behavior**
Three pods should match the service and be listed under pods. (Command output after applying my fixes:)

```console
PS C:\Users\Tobias Jacob\git\Prototype> kubectl get endpoints prototype-timescaledb
NAME                    ENDPOINTS                                            AGE
prototype-timescaledb   172.17.0.18:5432,172.17.0.19:5432,172.17.0.20:5432   8m31s
```

**Deployment**
- What is in your `values.yaml`: Standard values
- What version of the Chart are you using?: 0.13.1
- What is your Kubernetes Environment (for exampe: GKE, EKS, minikube, microk8s): minikube

**Deployment**
Please share some details of what is in your Kubernetes environment, for example:

```
kubectl get all,secret,configmap,endpoints,pvc -L role -l release=$RELEASE

PS C:\Users\Tobias Jacob\git\Prototype> kubectl get all,secret,configmap,endpoints,pvc -L role -l release=prototype
NAME                                                     READY   STATUS    RESTARTS        AGE    ROLE
pod/prototype-prometheus-alertmanager-5876cff56d-xvq7r   2/2     Running   2 (4h21m ago)   17h
pod/prototype-prometheus-node-exporter-mfg44             1/1     Running   1 (4h21m ago)   17h
pod/prototype-prometheus-pushgateway-868698c6bd-l295s    1/1     Running   1 (4h21m ago)   17h
pod/prototype-prometheus-server-75b4c68767-5wm7z         2/2     Running   2 (4h21m ago)   17h
pod/prototype-timescaledb-0                              2/2     Running   0               170m   master
pod/prototype-timescaledb-1                              2/2     Running   0               170m   replica
pod/prototype-timescaledb-2                              2/2     Running   0               169m   replica

NAME                                         TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)    AGE    ROLE
service/prototype-config                     ClusterIP   None             <none>        8008/TCP   170m
service/prototype-prometheus                 ClusterIP   10.100.39.55     <none>        9187/TCP   170m
service/prototype-prometheus-alertmanager    ClusterIP   10.107.157.225   <none>        80/TCP     17h
service/prototype-prometheus-node-exporter   ClusterIP   10.104.113.51    <none>        9100/TCP   17h
service/prototype-prometheus-pushgateway     ClusterIP   10.105.129.213   <none>        9091/TCP   17h
service/prototype-prometheus-server          ClusterIP   10.101.206.167   <none>        80/TCP     17h
service/prototype-replica                    ClusterIP   10.108.146.88    <none>        5432/TCP   170m   replica
service/prototype-timescaledb                ClusterIP   10.105.127.157   <none>        5432/TCP   124m   master

NAME                                                DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE   ROLE
daemonset.apps/prototype-prometheus-node-exporter   1         1         1       1            1           <none>          17h

NAME                                                READY   UP-TO-DATE   AVAILABLE   AGE   ROLE
deployment.apps/prototype-prometheus-alertmanager   1/1     1            1           17h
deployment.apps/prototype-prometheus-pushgateway    1/1     1            1           17h   
deployment.apps/prototype-prometheus-server         1/1     1            1           17h

NAME                                                           DESIRED   CURRENT   READY   AGE   ROLE
replicaset.apps/prototype-prometheus-alertmanager-5876cff56d   1         1         1       17h
replicaset.apps/prototype-prometheus-pushgateway-868698c6bd    1         1         1       17h
replicaset.apps/prototype-prometheus-server-75b4c68767         1         1         1       17h

NAME                                     READY   AGE    ROLE
statefulset.apps/prototype-timescaledb   3/3     170m

NAME                                          DATA   AGE    ROLE
configmap/prototype-prometheus-alertmanager   2      17h
configmap/prototype-prometheus-server         6      17h
configmap/prototype-timescaledb-patroni       1      170m
configmap/prototype-timescaledb-pgbackrest    1      170m
configmap/prototype-timescaledb-scripts       8      170m

NAME                                           ENDPOINTS                                            AGE     ROLE
endpoints/prototype                            172.17.0.18:5432                                     124m
endpoints/prototype-config                     172.17.0.18:8008,172.17.0.19:8008,172.17.0.20:8008   170m
endpoints/prototype-prometheus                 172.17.0.18:9187,172.17.0.19:9187,172.17.0.20:9187   170m
endpoints/prototype-prometheus-alertmanager    172.17.0.14:9093                                     17h
endpoints/prototype-prometheus-node-exporter   192.168.49.2:9100                                    17h
endpoints/prototype-prometheus-pushgateway     172.17.0.6:9091                                      17h
endpoints/prototype-prometheus-server          172.17.0.10:9090                                     17h
endpoints/prototype-replica                    172.17.0.19:5432,172.17.0.20:5432                    170m    replica
endpoints/prototype-timescaledb                172.17.0.18:5432,172.17.0.19:5432,172.17.0.20:5432   6m50s   master

NAME                                                           STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE    ROLE   
persistentvolumeclaim/prototype-prometheus-alertmanager        Bound    pvc-96d01889-1eeb-4a20-a93d-11cab2159d21   2Gi        RWO            standard       17h
persistentvolumeclaim/prototype-prometheus-server              Bound    pvc-81120dba-99be-4031-af57-630bc66209e3   8Gi        RWO            standard       17h
persistentvolumeclaim/storage-volume-prototype-timescaledb-0   Bound    pvc-5cf64a4e-28f2-485e-8519-3435bcdec439   2Gi        RWO            standard       18h
persistentvolumeclaim/storage-volume-prototype-timescaledb-1   Bound    pvc-4a0dd9ac-36a2-43b1-a1fd-99e295a6059d   64Gi       RWO            standard       170m
persistentvolumeclaim/storage-volume-prototype-timescaledb-2   Bound    pvc-b6a06c3b-adcb-45f2-822a-d1a0846d8ea0   64Gi       RWO            standard       169m
persistentvolumeclaim/wal-volume-prototype-timescaledb-0       Bound    pvc-78dadd26-6a2b-4211-96db-97d276de56b3   1Gi        RWO            standard       18h
persistentvolumeclaim/wal-volume-prototype-timescaledb-1       Bound    pvc-0f05273a-3749-4547-bb30-36def91212d6   1Gi        RWO            standard       170m
persistentvolumeclaim/wal-volume-prototype-timescaledb-2       Bound    pvc-f8f98486-5318-4a61-acc9-59395d73f86f   1Gi        RWO            standard       169m

```

**Logs**
No logs

**Additional context**
No additional context
