### ISSUE TITLE
[ISSUE] Primary service does not have a pod selector

### ISSUE THREAD

**Issue by fungiboletus** [timescale/timescaledb-kubernetes#394]
**Describe the bug**
Primary service does not have a pod selector when the loadBalancer is disabled.

**To Reproduce**

Deploy `timescaledb-single` with `loadBalancer.enabled` to `false`. Try to use the service, by doing a port forward for example.

**Expected behavior**

The service should have a selector.

**Deployment**
- What is in your `values.yaml`
  - ```yaml
    loadBalancer:
      enabled: false
    ```
- What version of the Chart are you using? `0.13.1`
- What is your Kubernetes Environment (for exampe: GKE, EKS, minikube, microk8s) N/A

**Deployment**

N/A

**Logs**

N/A

**Additional context**

Discussed here: https://github.com/timescale/timescaledb-kubernetes/issues/278

**Comment by dubiousdavid** [comment]
All that is need is to add the following under service.primary.spec in this file https://github.com/timescale/timescaledb-kubernetes/blob/master/charts/timescaledb-single/templates/svc-timescaledb.yaml:
```
selector:
    app: {{ template "timescaledb.fullname" . }}
    cluster-name: {{ template "clusterName" . }}
    role: master
```
