### ISSUE TITLE
Impossible to configure affinity

### ISSUE THREAD

**Issue by agronholm** [timescale/timescaledb-kubernetes#465]
**What happened?**

The chart's schema prevents users from specifying any values under the `affinity` key due to `additionalProperties: false`. The only possible value is thus an empty map.

**Did you expect to see something different?**

I expected to be able to define node affinity for the pods.

**How to reproduce it (as minimally and precisely as possible)**:

Deploy the chart with the configuration:

```yaml
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key: agentpool
              operator: In
              values:
                - dbpool
```

**Environment**

* Which helm chart and what version are you using?

timescaledb-single v0.16.3

* What is in your `values.yaml` ?

```yaml
timescaledb:
  clusterName: timescaledb
  image:
    pullPolicy: IfNotPresent
  secrets:
    credentialsSecretName: timescaledb-credentials
  replicaCount: 2
  loadBalancer:
    enabled: false
  persistentVolumes:
    data:
      size: 150Gi
      storageClass: managed-csi-premium
    wal:
      size: 5Gi
      storageClass: managed-csi-premium
  prometheus:
    enabled: true
  patroni:
    bootstrap:
      dcs:
        postgresql:
          parameters:
            ssl: 'off'
            idle_in_transaction_session_timeout: '900000'
            max_connections: "150"
    postgresql:
      create_replica_methods:
        - basebackup
      pg_hba:
        - local     all             postgres                              peer
        - local     all             all                                   md5
        - hostnossl all,replication all                all                md5
        - hostssl   all             all                127.0.0.1/32       md5
        - hostssl   all             all                ::1/128            md5
        - hostssl   replication     standby            all                md5
        - hostssl   all             all                all                md5
  timescaledbTune:
    args:
      max-conns: 150
  tolerations:
    - key: dedicated
      operator: Equal
      value: database
      effect: NoSchedule
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key: agentpool
              operator: In
              values:
                - dbpool
```

* Kubernetes version information: 

```
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.2", GitCommit:"5835544ca568b757a8ecae5c153f317e5736700e", GitTreeState:"clean", BuildDate:"2022-09-21T14:33:49Z", GoVersion:"go1.19.1", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.8", GitCommit:"a35ccc8395e8a5eaa83b7b8c981677893b651cba", GitTreeState:"clean", BuildDate:"2022-07-28T20:52:46Z", GoVersion:"go1.17.11", Compiler:"gc", Platform:"linux/amd64"}
```

    

* Kubernetes cluster kind: Azure AKS

**Anything else we need to know?**:
