### ISSUE TITLE
Changes in the dcs configuration are never applied

### ISSUE THREAD

**Issue by feikesteenbergen** [timescale/timescaledb-kubernetes#74]
When in the Helm chart, the section of the dcs is changed, for example:

```yaml
patroni:
  bootstrap:
    dcs:
      postgresql:
        parameters:
          max_wal_size: 1234MB
```

This change is correctly set on the `ConfigMap` that feeds Patroni, but the changes are not applied to the `RELEASE-config` endpoint, which is watched by Patroni.

To make this work correctly, we need to somehow patch the configuration of the `RELEASE_config` enpoint if and only iff the configuration has changed:

```console
kubecte get ep/RELEASE-config -o json \
  | jq '.metadata.annotations.config' -r \
  | jq '.postgresql.parameters.work_mem'
```
```json
"16MB"
```
