### ISSUE TITLE
HA setup with pg_prometheus extenstion

### ISSUE THREAD

**Issue by rleiwang** [timescale/timescaledb-kubernetes#84]
@feikesteenbergen thanks for creating this helm chart. 

If installing single node HA with image from https://hub.docker.com/r/timescale/pg_prometheus, does it leverage Patroni agent for HA failover?

**Comment by feikesteenbergen** [comment]
No, that Docker image does not contain Patroni.

However, the Docker image that is referred to in this repository *does* have `pg_prometheus` installed, so by setting the following in your `values.yaml` you should have `pg_prometheus` preloaded:

*myvalues.yaml*
```yaml
patroni:
  bootstrap:
    dcs:
      postgresql:
        parameters:
          shared_preload_libraries: timescaledb,pg_prometheus,pg_stat_statements
```

Afterwards, you can install the extension in any database:

```console
$ kubectl exec -ti pod/deployment-timescaledb-0 -- psql
psql (11.6 (Debian 11.6-1.pgdg100+1))
Type "help" for help.

postgres=# CREATE EXTENSION pg_prometheus;
CREATE EXTENSION
postgres=# \dx pg_prometheus
                     List of installed extensions
     Name      | Version | Schema |            Description            
---------------+---------+--------+-----------------------------------
 pg_prometheus | 0.2.2   | public | Prometheus metrics for PostgreSQL
(1 row)

postgres=# 
```
