### ISSUE TITLE
Patroni on Openshift patch endpoints/restricted

### ISSUE THREAD

**Issue by allen13** [timescale/timescaledb-kubernetes#91]
Openshift requires the role to include the endpoints/restricted resource otherwise it fails to update the endpoint due to permission errors.

Current:
https://github.com/timescale/timescaledb-kubernetes/blob/master/charts/timescaledb-single/templates/role-timescaledb.yaml#L31

Fixed:
```
- apiGroups: [""]
  resources: 
  - endpoints
  - endpoints/restricted
  verbs:
  - create
  - get
 ...
```
